name: stash_sembast
version: 1.0.0-dev.1
description: >-
  Disk storage extension for the stash caching API. Provides support to store caches
  int the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash_sembast

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  sembast: ^2.4.4
  stash:
    path: ../stash

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7
  test_coverage: ^0.4.1
