name: stash_sembast
version: 1.0.0-dev.3
description: >-
  Sembast storage extension for the stash caching API. Provides support to store caches
  int the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash_sembast

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  path: ^1.7.0
  sembast: ^2.4.7+6
  stash: ^1.0.0-dev.3
  #stash:
  #  path: ../stash

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.1
  test_coverage: ^0.4.3
